language: python
python:
 - "2.7"

# install Java 8 as required by vnu.jar
before_install:
 - sudo apt-get update
 - sudo apt-get install oracle-java8-installer
 - sudo update-java-alternatives -s java-8-oracle

install:
 - pip install html5validator==0.2.5

script: html5validator
